# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_contributor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='text_by', to='articles.Contributor'),
            preserve_default=False,
        ),
    ]
