# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20160907_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlerelatedlink',
            name='page',
        ),
        migrations.DeleteModel(
            name='ArticleRelatedLink',
        ),
    ]
