# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20161001_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='art_by', to='articles.Contributor'),
        ),
    ]
