# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('months', '0002_auto_20160911_2308'),
        ('articles', '0004_auto_20160909_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_theme', to='months.Months'),
        ),
    ]
