# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20161001_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='art_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='art_by', to='articles.Contributor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='text_by', to='articles.Contributor'),
        ),
    ]
