# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20161006_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_image_float',
            field=models.BooleanField(default=False, help_text='Should the image float vertically on the details page'),
        ),
    ]
