# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 23:48
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_main_image_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='__str__'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image_float',
            field=models.BooleanField(default=False, help_text='Select if the image should float vertically on the details page', verbose_name='Float Image'),
        ),
    ]
