# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 00:04
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20161017_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='__str__'),
        ),
    ]
