# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161014_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='feature_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_image', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='feature_text',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
    ]
