# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('months', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Months',
            new_name='Month',
        ),
    ]
