# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_contributor_image'),
        ('months', '0004_auto_20160918_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to='articles.Article'),
        ),
    ]
