# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_contributor_image'),
        ('months', '0005_month_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='feature_girl_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_girl_1', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='month',
            name='feature_girl_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_girl_2', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='month',
            name='music_spotlight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_spotlight', to='articles.Article'),
        ),
    ]
