# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 00:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('months', '0006_auto_20160926_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='feature_girl_1',
            field=models.ForeignKey(blank=True, help_text='Feature Girl #1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_girl_1', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='month',
            name='feature_girl_2',
            field=models.ForeignKey(blank=True, help_text='Feature Girl #2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_girl_2', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='month',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='Leader of the Month', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='month',
            name='music_spotlight',
            field=models.ForeignKey(blank=True, help_text='Music Spotlight', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_spotlight', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2010)]),
        ),
    ]
