# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 18:15
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('months', '0007_auto_20161001_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Text to display in sidebar theme box'),
        ),
    ]
